# Generated by Django 5.2.10 on 2026-01-21 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_course_coursepurchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='department',
            new_name='education',
        ),
    ]
